version: "3.9"

services:
  himalia:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./scripts:/app/scripts
      - ./reports:/data/reports
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host